from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol, Iterable, Sequence, Optional

# ============== DTOs ==============

@dataclass
class ComposeContext:
    environment: str  # "dev" | "prod"
    compose_file: Path
    work_dir: Path
    project_name: str

@dataclass
class BuildResult:
    ok: bool
    message: str = ""

# ============== Interfaces (Protocols) ==============

class Shell(Protocol):
    def run(self, cmd: Sequence[str], cwd: Optional[Path] = None, check: bool = True) -> int: ...
    def run_capture(self, cmd: Sequence[str], cwd: Optional[Path] = None) -> tuple[int, str, str]: ...
    def popen_stream(self, cmd: Sequence[str], cwd: Optional[Path] = None) -> int: ...

class Progress(Protocol):
    def task(self, total: int, desc: str, unit: str = "") -> "ProgressTask": ...

class ProgressTask(Protocol):
    def set_description(self, desc: str) -> None: ...
    def update(self, n: int = 1) -> None: ...
    def close(self) -> None: ...

class DockerService(Protocol):
    def is_available(self) -> bool: ...
    def images_exist(self, images: Iterable[str]) -> bool: ...
    def image_exists(self, name: str) -> bool: ...
    def load_image_tar(self, tar_path: Path) -> bool: ...
    def save_image_tar(self, image: str, target: Path) -> bool: ...
    def build_image(self, tag: str, context: Path, dockerfile: Optional[Path] = None, platforms: Optional[Sequence[str]] = None) -> bool: ...
    def pull_image(self, image: str, platform: Optional[str] = None) -> bool: ...
    def prepare_images(self, env: str, images: Iterable[str], image_cache_dir: Path, deploy_dir: Path, questdb_dir: Path, platform: Optional[str] = None) -> bool: ...
    def ps_table(self) -> str: ...

class DotnetService(Protocol):
    def is_available(self) -> bool: ...
    def publish(self, rid: Optional[str], output: Path) -> BuildResult: ...
    def build_environment(self, env: str, release_dir: Path) -> bool: ...
    def sync_runtime_assets(self, env: str, release_dir: Path) -> None: ...
    def run_packetprocessing(self, dll_path: Path, environment: str, detach: bool = False) -> int: ...
    def terminate_packetprocessing(self, dll_path: Path, environment: str) -> None: ...
    def project_exists(self) -> bool: ...

class ComposeService(Protocol):
    def build(self, ctx: ComposeContext, no_cache: bool = False) -> bool: ...
    def up(self, ctx: ComposeContext, detached: bool, build_if_missing: bool = True) -> bool: ...
    def stop(self, ctx: ComposeContext) -> bool: ...
    def remove(self, ctx: ComposeContext) -> bool: ...
    def logs_follow(self, ctx: ComposeContext) -> None: ...

class PackagingService(Protocol):
    def create_release(self, platform: str) -> bool: ...

class EnvManager(Protocol):
    def is_running(self, ctx: ComposeContext) -> bool: ...
    def stop_env(self, ctx: ComposeContext) -> bool: ...
    def kill_env(self, ctx: ComposeContext) -> bool: ...

# High-level app protocol
class ComposerUseCases(Protocol):
    def up(self, environment: str, detached: bool) -> int: ...
    def stop(self, environment: str) -> int: ...
    def kill(self, environment: str) -> int: ...
    def status(self) -> int: ...
    def build_all(self) -> int: ...
    def release(self, platform: str) -> int: ...
