using PacketProcessing.Utils.Enums;

namespace PacketProcessing.Utils.Parsers.MotionUtilities;

public static class MotionCommands
{
    public static readonly Dictionary<int, MotionRecord> MotionRecords = new()
    {
        // Get data commands
        { 0x0106, new MotionRecord("MOT_GetMotorCurrent", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0107, new MotionRecord("MOT_GetMotorVoltage", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0108, new MotionRecord("MOT_GetMotorPosition", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0109, new MotionRecord("MOT_GetLoadPosition", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x010A, new MotionRecord("MOT_GetMotorSpeed", ValueTypes.None, ValueTypes.Float32BE) },
        
        // Motion Registers & Utils
        { 0x0101, new MotionRecord("MOT_MerRegister", ValueTypes.None, ValueTypes.UInt16BE) },
        { 0x0102, new MotionRecord("MOT_DerRegister", ValueTypes.None, ValueTypes.UInt16BE) },
        { 0x0103, new MotionRecord("MOT_SrhRegister", ValueTypes.None, ValueTypes.UInt16BE) },
        { 0x0104, new MotionRecord("MOT_SrlRegister", ValueTypes.None, ValueTypes.UInt16BE) },
        { 0x0105, new MotionRecord("MOT_MsrRegister", ValueTypes.None, ValueTypes.UInt16BE) },
        { 0x010C, new MotionRecord("MOT_GetNegSWLS", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x010D, new MotionRecord("MOT_GetPosSWLS", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0110, new MotionRecord("MOT_IsActiveSWLS", ValueTypes.None, ValueTypes.UInt8) },
        { 0x014F, new MotionRecord("MOT_GetShortPath", ValueTypes.None, ValueTypes.UInt8) },
        { 0x012E, new MotionRecord("MOT_GetMaxCurrent", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0130, new MotionRecord("MOT_SetAcceleration", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0131, new MotionRecord("MOT_SetSpeed", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0132, new MotionRecord("MOT_SendPosition", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0133, new MotionRecord("MOT_SetActualPosition", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0134, new MotionRecord("MOT_Update", ValueTypes.None, ValueTypes.None) },
        { 0x0135, new MotionRecord("MOT_Homing", ValueTypes.None, ValueTypes.None) },
        { 0x0136, new MotionRecord("MOT_SetNegSWLS", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0137, new MotionRecord("MOT_SetPosSWLS", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0146, new MotionRecord("MOT_ActivateSWLS", ValueTypes.UInt8, ValueTypes.None) },
        { 0x0138, new MotionRecord("MOT_SetPositionRelative", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0139, new MotionRecord("MOT_SetPositionAbsolute", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x013A, new MotionRecord("MOT_SetSpeedMode", ValueTypes.None, ValueTypes.None) },
        { 0x013B, new MotionRecord("MOT_SetPositionMode", ValueTypes.None, ValueTypes.None) },
        { 0x013C, new MotionRecord("MOT_AxisOn", ValueTypes.None, ValueTypes.None) },
        { 0x013D, new MotionRecord("MOT_AxisOff", ValueTypes.None, ValueTypes.None) },
        { 0x013E, new MotionRecord("MOT_AxisReset", ValueTypes.None, ValueTypes.None) },
        { 0x013F, new MotionRecord("MOT_SetTum", ValueTypes.UInt8, ValueTypes.None) },
        { 0x0143, new MotionRecord("MOT_ResetFaults", ValueTypes.None, ValueTypes.None) },
        { 0x014E, new MotionRecord("MOT_SetShortPath", ValueTypes.UInt8, ValueTypes.None) },
        { 0x0165, new MotionRecord("MOT_SaveMotorSetting", ValueTypes.None, ValueTypes.None) },
        { 0x0166, new MotionRecord("MOT_SetMaxCurrent", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0144, new MotionRecord("MOT_SetMotionComplete", ValueTypes.None, ValueTypes.None) },

        // SCAN commands (SCN)
        { 0x0400, new MotionRecord("SCN_SetYawMin", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0401, new MotionRecord("SCN_SetYawMax", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0402, new MotionRecord("SCN_SetPitchMin", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0403, new MotionRecord("SCN_SetNumSteps", ValueTypes.UInt32BE, ValueTypes.None) },
        { 0x0404, new MotionRecord("SCN_SetStepHeight", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0405, new MotionRecord("SCN_SetScanSpeed", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0406, new MotionRecord("SCN_SetShortPath", ValueTypes.UInt8, ValueTypes.None) },
        { 0x0407, new MotionRecord("SCN_IsScanOn", ValueTypes.None, ValueTypes.UInt8) },
        { 0x0408, new MotionRecord("SCN_StopScan", ValueTypes.None, ValueTypes.None) },
        { 0x040C, new MotionRecord("SCN_StartScanZigZag", ValueTypes.None, ValueTypes.None) },
        { 0x040D, new MotionRecord("SCN_StartScanSnake", ValueTypes.None, ValueTypes.None) },
        { 0x040E, new MotionRecord("SCN_StartScanSquare", ValueTypes.None, ValueTypes.None) },

        // COM commands
        { 0x0700, new MotionRecord("COM_Reboot", ValueTypes.None, ValueTypes.None) },
        { 0x0702, new MotionRecord("COM_Connect", ValueTypes.None, ValueTypes.None) },
        { 0x0703, new MotionRecord("COM_Disconnect", ValueTypes.None, ValueTypes.None) },
        { 0x0704, new MotionRecord("COM_IsConnected", ValueTypes.None, ValueTypes.UInt8) },
        { 0x0705, new MotionRecord("COM_StartKeepAlive", ValueTypes.None, ValueTypes.None) },
        { 0x0706, new MotionRecord("COM_IsKeepAliveOn", ValueTypes.None, ValueTypes.UInt8) },
        { 0x0708, new MotionRecord("COM_setKeepAliveTimeout", ValueTypes.UInt32BE, ValueTypes.None) },
        { 0x0709, new MotionRecord("COM_getKeepAliveTimeout", ValueTypes.None, ValueTypes.UInt32BE) },
        { 0x071C, new MotionRecord("COM_setKeepAliveCount", ValueTypes.UInt32BE, ValueTypes.None) },
        { 0x071D, new MotionRecord("COM_getKeepAliveCount", ValueTypes.None, ValueTypes.UInt32BE) },
        { 0x0719, new MotionRecord("COM_SetComType", ValueTypes.UInt8, ValueTypes.None) },
        { 0x0713, new MotionRecord("COM_SysState", ValueTypes.None, ValueTypes.UInt8) },
        
        // IP Config
        { 0x070A, new MotionRecord("IP_SetControllerIP", ValueTypes.UInt32BE, ValueTypes.None) },
        { 0x070D, new MotionRecord("IP_GetControllerIP", ValueTypes.None, ValueTypes.UInt32BE) },
        { 0x070B, new MotionRecord("IP_SetControllerPort", ValueTypes.UInt16BE, ValueTypes.None) },
        { 0x070E, new MotionRecord("IP_GetControllerPort", ValueTypes.None, ValueTypes.UInt16BE) },
        { 0x071A, new MotionRecord("IP_SetControllerSubnetMask", ValueTypes.UInt32BE, ValueTypes.None) },
        { 0x0710, new MotionRecord("IP_SaveIP", ValueTypes.None, ValueTypes.None) },

        // Device Info
        { 0x0C2D, new MotionRecord("COM_GetPn", ValueTypes.None, ValueTypes.UInt32BE) },
        { 0x0C2F, new MotionRecord("COM_GetSn", ValueTypes.None, ValueTypes.UInt32BE) },
        { 0x0C4A, new MotionRecord("COM_GetFw", ValueTypes.None, ValueTypes.UInt32BE) },
        { 0x0C4C, new MotionRecord("COM_GetHw", ValueTypes.None, ValueTypes.UInt32BE) },

        // LRF commands
        { 0x0300, new MotionRecord("LRF_SetRange", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0301, new MotionRecord("LRF_GetRange", ValueTypes.None, ValueTypes.Float32BE) },
        
        // Stabilization (STB)
        { 0x0800, new MotionRecord("STB_StabilizationOn", ValueTypes.None, ValueTypes.None) },
        { 0x0801, new MotionRecord("STB_StabilizationOff", ValueTypes.None, ValueTypes.None) },
        { 0x0822, new MotionRecord("STB_GetStabError", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0839, new MotionRecord("STB_SetStabMinAccel", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x083A, new MotionRecord("STB_GetStabMinAccel", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0D04, new MotionRecord("STB_SetSpdKp", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0D08, new MotionRecord("STB_GetSpdKp", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0D05, new MotionRecord("STB_SetSpdKi", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0D09, new MotionRecord("STB_GetSpdKi", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0D06, new MotionRecord("STB_SetSpdKd", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0D0A, new MotionRecord("STB_GetSpdKd", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0D16, new MotionRecord("STB_SetPosKp", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0D17, new MotionRecord("STB_GetPosKp", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0D18, new MotionRecord("STB_SetPosKi", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0D19, new MotionRecord("STB_GetPosKi", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0D1A, new MotionRecord("STB_SetPosKd", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0D1B, new MotionRecord("STB_GetPosKd", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x082B, new MotionRecord("STB_SetDistanceToTarget", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x082A, new MotionRecord("STB_GetDistanceToTarget", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0825, new MotionRecord("STB_SetCentralAxes", ValueTypes.UInt8, ValueTypes.None) },
        { 0x0826, new MotionRecord("STB_GetCentralAxes", ValueTypes.None, ValueTypes.UInt8) },
        { 0x0C76, new MotionRecord("STB_SetRollCompensation", ValueTypes.UInt8, ValueTypes.None) },
        { 0x0C77, new MotionRecord("STB_GetRollCompensation", ValueTypes.None, ValueTypes.UInt8) },
        { 0x084F, new MotionRecord("STB_SetRebalanceOn", ValueTypes.None, ValueTypes.None) },
        { 0x0850, new MotionRecord("STB_GetRebalanceOn", ValueTypes.None, ValueTypes.UInt8) },
        { 0x0851, new MotionRecord("STB_GetRebalanceStatus", ValueTypes.None, ValueTypes.UInt8) },
        { 0x0D07, new MotionRecord("STB_SaveStabilizationCfg", ValueTypes.None, ValueTypes.None) },

        // Dual Gimbals (DG)
        { 0x0FA0, new MotionRecord("DG_SetSyncMode", ValueTypes.UInt8, ValueTypes.None) },
        { 0x0FA1, new MotionRecord("DG_SetInnerMode", ValueTypes.UInt8, ValueTypes.None) },
        { 0x0FA2, new MotionRecord("DG_IsSyncMode", ValueTypes.None, ValueTypes.UInt8) },
        { 0x0FA3, new MotionRecord("DG_IsInnerMode", ValueTypes.None, ValueTypes.UInt8) },
        { 0x0FA5, new MotionRecord("DG_GetPosDiff", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0FA6, new MotionRecord("DG_SetMaxDiff", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0FA7, new MotionRecord("DG_GetMaxDiff", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0FA9, new MotionRecord("DG_GoToCamera", ValueTypes.UInt8, ValueTypes.None) },
        { 0x0FAA, new MotionRecord("DG_SetSyncSpd", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0FAB, new MotionRecord("DG_SetMainGimbal", ValueTypes.UInt8, ValueTypes.None) },
        { 0x0FAC, new MotionRecord("DG_GetMainGimbal", ValueTypes.None, ValueTypes.UInt8) },
        { 0x0FB0, new MotionRecord("DG_CTC", ValueTypes.None, ValueTypes.None) },
        { 0x0FB1, new MotionRecord("DG_GetCTCoffset", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0FB2, new MotionRecord("DG_ResetCTCoffset", ValueTypes.None, ValueTypes.None) },
        { 0x0FB5, new MotionRecord("DG_GetSyncSpd", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0FB6, new MotionRecord("DG_SetActiveWeapon", ValueTypes.UInt8, ValueTypes.None) },
        { 0x0FB7, new MotionRecord("DG_GetActiveWeapon", ValueTypes.None, ValueTypes.UInt8) },
        { 0x0FB9, new MotionRecord("DG_IsBoresightEn", ValueTypes.None, ValueTypes.UInt8) },
        { 0x0FBA, new MotionRecord("DG_SetActiveCamera", ValueTypes.UInt8, ValueTypes.None) },
        { 0x0FBB, new MotionRecord("DG_GetActiveCamera", ValueTypes.None, ValueTypes.UInt8) },
        { 0x0FBC, new MotionRecord("DG_GetBoresightOffset", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0FBD, new MotionRecord("DG_SetBallisticOffset", ValueTypes.Float32BE, ValueTypes.None) },
        { 0x0FBE, new MotionRecord("DG_GetBallisticOffset", ValueTypes.None, ValueTypes.Float32BE) },
        { 0x0FBF, new MotionRecord("DG_GetSafetyStatus", ValueTypes.None, ValueTypes.UInt8) },
        { 0x0FC0, new MotionRecord("DG_GetLoadStatus", ValueTypes.None, ValueTypes.UInt8) },
        { 0x0FC1, new MotionRecord("DG_GetCapsnapIOStatus", ValueTypes.None, ValueTypes.UInt16BE) },
        { 0x0FC2, new MotionRecord("DG_GetNumBullets", ValueTypes.None, ValueTypes.UInt16BE) },
        { 0x0FC3, new MotionRecord("DG_ResetNumBullets", ValueTypes.None, ValueTypes.None) },
        { 0x0FC4, new MotionRecord("DG_IsCapSnapReady", ValueTypes.None, ValueTypes.UInt8) },

        // ERROR commands (ERR)
        { 0x0E01, new MotionRecord("ERR_CaptureSystemRegister", ValueTypes.None, ValueTypes.UInt32BE) },
        { 0x0E02, new MotionRecord("ERR_ClearErrors", ValueTypes.None, ValueTypes.None) },
        { 0x0E03, new MotionRecord("ERR_GetDriverErrorString", ValueTypes.None, ValueTypes.None) },
        { 0x0E04, new MotionRecord("ERR_GetSystemErrorString", ValueTypes.None, ValueTypes.None) },
        { 0x0E05, new MotionRecord("ERR_GetLoadImuErrorString", ValueTypes.None, ValueTypes.None) },
        { 0x0E06, new MotionRecord("ERR_GetBaseImuErrorString", ValueTypes.None, ValueTypes.None) },
        { 0x0E07, new MotionRecord("ERR_GetGpsComErrorString", ValueTypes.None, ValueTypes.None) },
        { 0x0E08, new MotionRecord("ERR_GetGpsPosString", ValueTypes.None, ValueTypes.None) },
        { 0x0E09, new MotionRecord("ERR_GetGpsHeadErrorString", ValueTypes.None, ValueTypes.None) },
        { 0x0E0A, new MotionRecord("ERR_GetProtocolErrorString", ValueTypes.None, ValueTypes.None) },
        { 0x0E0D, new MotionRecord("ERR_GetAbsEncComErrorString", ValueTypes.None, ValueTypes.None) },
        { 0x0E0E, new MotionRecord("ERR_GetAbsEncCRCErrorString", ValueTypes.None, ValueTypes.None) },
        { 0x0E0F, new MotionRecord("ERR_GetBodyImuErrorString", ValueTypes.None, ValueTypes.None) },
        { 0x0E10, new MotionRecord("ERR_GetHomingErrorString", ValueTypes.None, ValueTypes.None) },
        { 0x0E12, new MotionRecord("ERR_OperationRegister", ValueTypes.None, ValueTypes.UInt16BE) },
    };
}